Repository GuchiTheHasky/Alta, pull requests merged in 2024-02, with the labels that each got.

#66 Change the response of findAllUnfinishedTasks method into two lists
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/entity/TasksResponse.java
Labels: backend

#67 update tasks table to receive two lists
  alta-back-end/logs/alta.log
  alta-front-end/src/api/tasks/dto/tasks-response.dto.ts
  alta-front-end/src/pages/tasks/tasks-table.component.jsx.tsx
  alta-front-end/src/pages/tasks/tasks.tsx
Labels: frontend

#71 change lists of integers ids to lists of objects
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/entity/ModelRequest.java
  alta-back-end/src/main/java/com/alta/web/entity/TasksRequest.java
  alta-front-end/src/api/students/dto/students-response.dto.ts
  alta-front-end/src/api/tasks/dto/tasks-response.dto.ts
  alta-front-end/src/api/topics/dto/topics-response.dto.ts
  alta-front-end/src/context/data-provider.context.tsx
  alta-front-end/src/pages/students/students-table.component.tsx
  alta-front-end/src/pages/students/students.tsx
  alta-front-end/src/pages/tasks/modal.tsx
  alta-front-end/src/pages/tasks/tasks-table.component.jsx.tsx
  alta-front-end/src/pages/tasks/tasks.tsx
  alta-front-end/src/pages/topics/topics-table.component.tsx
  alta-front-end/src/pages/topics/topics.tsx
Labels: backend, frontend

#73 fix multy select for completed tasks
  alta-front-end/src/pages/tasks/tasks-table.component.jsx.tsx
Labels: frontend

#74 Remove unnecessary code, rename some methods, edit documentation
  alta-back-end/src/main/java/com/alta/dto/StudentDto.java
  alta-back-end/src/main/java/com/alta/dto/TaskDto.java
  alta-back-end/src/main/java/com/alta/dto/TopicDto.java
  alta-back-end/src/main/java/com/alta/entity/Student.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/entity/Topic.java
  alta-back-end/src/main/java/com/alta/exception/TaskException.java
  alta-back-end/src/main/java/com/alta/exception/TopicException.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/BasicMainFacade.java
  alta-back-end/src/main/java/com/alta/mapper/StudentMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TaskMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TopicMapper.java
  alta-back-end/src/main/java/com/alta/repository/StudentRepository.java
  alta-back-end/src/main/java/com/alta/repository/TaskRepository.java
  alta-back-end/src/main/java/com/alta/repository/TopicRepository.java
  alta-back-end/src/main/java/com/alta/service/StudentService.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/TopicService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultStudentService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTopicService.java
  alta-back-end/src/main/java/com/alta/web/controller/StudentController.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/controller/TopicController.java
  alta-back-end/src/main/java/com/alta/web/entity/TasksRequest.java
Labels: backend

#75 modal window works
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/BasicMainFacade.java
  alta-back-end/src/main/java/com/alta/repository/TopicRepository.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-front-end/src/context/data-provider.context.tsx
  alta-front-end/src/pages/tasks/modal.tsx
  alta-front-end/src/pages/tasks/tasks-table.component.jsx.tsx
  alta-front-end/src/pages/topics/topics.tsx
Labels: frontend

#77 added page without answers
  alta-front-end/src/pages/tasks/tasks.tsx
Labels: frontend

#82 update task mapper, aded method update
  .gitignore
  alta-back-end/src/main/java/com/alta/dto/TaskDto.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/mapper/TaskMapper.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
Labels: backend

#83 added new flyway scripts; new tasks responce; refactored front-end;
  alta-back-end/src/main/java/com/alta/dto/TaskDto.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/entity/TaskStatus.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/BasicMainFacade.java
  alta-back-end/src/main/java/com/alta/mapper/StudentMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TaskMapper.java
  alta-back-end/src/main/java/com/alta/repository/TaskRepository.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/entity/TasksResponse.java
  alta-back-end/src/main/resources/db.migration/V2.0__Add_task_status.sql
  alta-back-end/src/main/resources/db.migration/V2.1__DB_refactoring_drop_redundant_columns.sql
  alta-front-end/src/api/tasks/dto/tasks-response.dto.ts
  alta-front-end/src/mocks/browser.ts
  alta-front-end/src/mocks/data/students.mock.ts
  alta-front-end/src/mocks/handlers.ts
  alta-front-end/src/pages/tasks/image.tsx
  alta-front-end/src/pages/tasks/tasks-table.component.jsx.tsx
  alta-front-end/src/pages/tasks/tasks.tsx
  alta-front-end/src/pages/topics/topics.tsx
Labels: backend, frontend

#84 tailwind config update
  alta-front-end/src/components/buttons/green-button.component.tsx
  alta-front-end/src/pages/tasks/modal.tsx
  alta-front-end/tailwind.config.js
Labels: frontend

#87 first relise refactoring
  alta-back-end/pom.xml
  alta-back-end/src/main/java/com/alta/dto/StudentDto.java
  alta-back-end/src/main/java/com/alta/dto/TaskDto.java
  alta-back-end/src/main/java/com/alta/entity/Student.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/entity/TasksGroup.java
  alta-back-end/src/main/java/com/alta/exception/TaskGroupException.java
  alta-back-end/src/main/java/com/alta/exception/TopicException.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/BasicMainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/mapper/StudentMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TaskMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TopicMapper.java
  alta-back-end/src/main/java/com/alta/repository/StudentRepository.java
  alta-back-end/src/main/java/com/alta/repository/TaskGroupRepository.java
  alta-back-end/src/main/java/com/alta/repository/TaskRepository.java
  alta-back-end/src/main/java/com/alta/repository/TopicRepository.java
  alta-back-end/src/main/java/com/alta/service/StudentService.java
  alta-back-end/src/main/java/com/alta/service/TaskGroupService.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/TopicService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultStudentService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskGroupService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/web/controller/StudentController.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskGroupController.java
  alta-back-end/src/main/java/com/alta/web/controller/TopicController.java
  alta-back-end/src/main/java/com/alta/web/entity/ModelRequest.java
  alta-back-end/src/main/java/com/alta/web/entity/TaskRequest.java
  alta-back-end/src/main/java/com/alta/web/entity/TaskResponse.java
  alta-back-end/src/main/java/com/alta/web/entity/TasksRequest.java
  alta-back-end/src/main/java/com/alta/web/entity/TasksResponse.java
  alta-back-end/src/main/resources/db.migration/V2.2__Initial_tasks_group_table.sql
  alta-back-end/src/main/resources/templates/with_answer.html
  alta-back-end/src/main/resources/templates/without_answer.html
Labels: backend

#95 added tg mapper
  alta-back-end/src/main/java/com/alta/dto/TaskDto.java
  alta-back-end/src/main/java/com/alta/dto/TasksGroupDto.java
  alta-back-end/src/main/java/com/alta/entity/TaskStatus.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/mapper/TaskGroupMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TaskMapper.java
  alta-back-end/src/main/java/com/alta/service/StudentService.java
  alta-back-end/src/main/java/com/alta/service/TaskGroupService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultStudentService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskGroupService.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskGroupController.java
  alta-back-end/src/main/java/com/alta/web/entity/TaskResponse.java
  alta-back-end/src/main/resources/templates/with_answer.html
  alta-back-end/src/main/resources/templates/without_answer.html
  alta-back-end/src/test/java/com/alta/web/controller/StudentControllerTest.java
  alta-back-end/src/test/java/com/alta/web/controller/TaskControllerTest.java
Labels: backend
