Repository GuchiTheHasky/Alta, pull requests merged in 2024-01, with the labels that each got.

#45 added posibility to load template with answers
  .gitignore
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/repository/TaskRepository.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/resources/templates/task_list_answers.html
  alta-front-end/src/api/context/appContext.tsx
  alta-front-end/src/api/students/useGetStudents.ts
  alta-front-end/src/api/tasks/useGetTasks.ts
  alta-front-end/src/assets/vite.svg
  alta-front-end/src/components/header/header.component.tsx
  alta-front-end/src/modules/tasks/tasks-table.component.tsx
  alta-front-end/src/pages/students.tsx
  alta-front-end/src/pages/tasks.tsx
  alta-front-end/src/pages/topics.tsx
  alta-front-end/vite.config.ts
  alta-front-end/vite.svg
Labels: backend, frontend

#47 added server port 3000
  alta-front-end/vite.config.ts
Labels: frontend

#48 added facade; tasks filter; update services; change bond between stud…
  .gitignore
  alta-back-end/src/main/java/com/alta/entity/Student.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/repository/StudentRepository.java
  alta-back-end/src/main/java/com/alta/repository/TaskRepository.java
  alta-back-end/src/main/java/com/alta/service/StudentService.java
  alta-back-end/src/main/java/com/alta/service/TaskFilter.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/TopicService.java
  alta-back-end/src/main/java/com/alta/service/ZnoService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultStudentService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskFilter.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/web/controller/StudentController.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/controller/TopicController.java
  alta-back-end/src/main/resources/db.migration/V1.5__Alter_table_students_add_new_col.sql
  alta-front-end/src/pages/tasks.tsx
  alta-front-end/src/pages/topics.tsx
Labels: backend, frontend

#49 Edit Student and Task
  alta-back-end/src/main/java/com/alta/entity/Student.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/mapper/StudentMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TaskMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TopicMapper.java
  alta-back-end/src/main/java/com/alta/service/StudentService.java
  alta-back-end/src/main/java/com/alta/service/TaskFilter.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/TopicService.java
  alta-back-end/src/main/java/com/alta/service/ZnoService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultStudentService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTopicService.java
  alta-back-end/src/main/java/com/alta/web/controller/StudentController.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/controller/TopicController.java
  alta-back-end/src/main/resources/db.migration/V1.6_Alter_table_task_and_students_drop_columns.sql
  alta-back-end/src/main/resources/templates/task_list.html
  alta-back-end/src/main/resources/templates/task_list_answers.html
  alta-front-end/src/pages/tasks.tsx
Labels: backend, frontend

#52 added modal form for edit tasks
  alta-back-end/src/main/resources/db.migration/V1.6_Alter_table_task_and_students_drop_columns.sql
  alta-back-end/src/main/resources/db.migration/V1.6__Alter_table_task_and_students_drop_columns.sql
  alta-front-end/package.json
  alta-front-end/src/api/tasks/dto/tasks-response.dto.ts
  alta-front-end/src/components/buttons/yellow-button.component.tsx
  alta-front-end/src/modules/tasks/content/table-columns.content.tsx
  alta-front-end/src/modules/tasks/modal/entity.ts
  alta-front-end/src/modules/tasks/modal/modal-button.tsx
  alta-front-end/src/modules/tasks/modal/modal-edit-button.tsx
  alta-front-end/src/modules/tasks/modal/mui-modal.tsx
  alta-front-end/src/modules/tasks/tasks-table.component.tsx
  alta-front-end/src/pages/tasks.tsx
  alta-front-end/src/pages/topics.tsx
  alta-front-end/tsconfig.json
  alta-front-end/yarn.lock
Labels: backend, frontend

#51 Change relationships @OneToMany between Topic and Task Entity-classes…
  alta-back-end/src/main/java/com/alta/dto/TaskDto.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/entity/Topic.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/mapper/TaskMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TopicMapper.java
  alta-back-end/src/main/java/com/alta/repository/TaskRepository.java
  alta-back-end/src/main/java/com/alta/repository/TopicRepository.java
  alta-back-end/src/main/java/com/alta/service/TaskFilter.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/TopicService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskFilter.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTopicService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultZnoService.java
  alta-back-end/src/main/resources/db.migration/V1.6__Alter_table_task_and_students_drop_columns.sql
  alta-back-end/src/main/resources/db.migration/V1.7__Alter_table_topic_add_new_column.sql
  alta-back-end/src/main/resources/templates/task_list.html
  alta-back-end/src/main/resources/templates/task_list_answers.html
Labels: backend

#54 Refactoring 22 01
  .gitignore
  alta-back-end/src/main/java/com/alta/AltaStarter.java
  alta-back-end/src/main/java/com/alta/config/WebConfiguration.java
  alta-back-end/src/main/java/com/alta/dto/StudentDto.java
  alta-back-end/src/main/java/com/alta/dto/TaskDto.java
  alta-back-end/src/main/java/com/alta/dto/TopicDto.java
  alta-back-end/src/main/java/com/alta/dto/ZnoDto.java
  alta-back-end/src/main/java/com/alta/entity/Student.java
  alta-back-end/src/main/java/com/alta/entity/Task.java
  alta-back-end/src/main/java/com/alta/entity/Topic.java
  alta-back-end/src/main/java/com/alta/exception/TaskException.java
  alta-back-end/src/main/java/com/alta/exception/ZnoException.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/mapper/StudentMapper.java
  alta-back-end/src/main/java/com/alta/mapper/TopicMapper.java
  alta-back-end/src/main/java/com/alta/mapper/ZnoMapper.java
  alta-back-end/src/main/java/com/alta/repository/StudentRepository.java
  alta-back-end/src/main/java/com/alta/repository/TaskRepository.java
  alta-back-end/src/main/java/com/alta/repository/TopicRepository.java
  alta-back-end/src/main/java/com/alta/repository/ZnoRepository.java
  alta-back-end/src/main/java/com/alta/service/StudentService.java
  alta-back-end/src/main/java/com/alta/service/TaskFilter.java
  alta-back-end/src/main/java/com/alta/service/TaskService.java
  alta-back-end/src/main/java/com/alta/service/TopicService.java
  alta-back-end/src/main/java/com/alta/service/ZnoService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultStudentService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskFilter.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTaskService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTopicService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultZnoService.java
  alta-back-end/src/main/java/com/alta/web/controller/TaskController.java
  alta-back-end/src/main/java/com/alta/web/controller/TopicController.java
  alta-back-end/src/main/java/com/alta/web/controller/ZnoController.java
  alta-back-end/src/main/resources/db.migration/V1.8__Alter_table_task.sql
  alta-back-end/src/main/resources/db.migration/V1.9__Initial_many_to_many_bond.sql
  alta-back-end/src/test/java/com/alta/web/controller/ZnoControllerITest.java
  alta-front-end/package.json
  alta-front-end/src/App.tsx
  alta-front-end/src/api/context/appContext.tsx
  alta-front-end/src/api/students/dto/students-response.dto.ts
  alta-front-end/src/api/students/useGetStudents.ts
  alta-front-end/src/api/tasks/useGetTasks.ts
  alta-front-end/src/api/topics/dto/topics-response.dto.ts
  alta-front-end/src/api/topics/useGetTopics.ts
  alta-front-end/src/modules/students/content/table-columns.content.tsx
  alta-front-end/src/modules/students/students-table.component.tsx
  alta-front-end/src/modules/tasks/content/table-columns.content.tsx
  alta-front-end/src/modules/tasks/modal/ModalButton.tsx
  alta-front-end/src/modules/tasks/modal/entity.ts
  alta-front-end/src/modules/tasks/modal/modal-button.tsx
  alta-front-end/src/modules/tasks/modal/modal-edit-button.tsx
  alta-front-end/src/modules/tasks/modal/mui-modal.tsx
  alta-front-end/src/modules/tasks/tasks-table.component.tsx
  alta-front-end/src/modules/topics/content/table-columns.content.ts
  alta-front-end/src/modules/topics/topics-table.component.tsx
  alta-front-end/src/pages/students.tsx
  alta-front-end/src/pages/tasks.tsx
  alta-front-end/src/pages/topics.tsx
  alta-front-end/yarn.lock
Labels: backend, frontend

#55 remove redundant code and comments
  alta-front-end/src/api/students/useGetStudents.ts
  alta-front-end/src/api/tasks/dto/tasks-response.dto.ts
  alta-front-end/src/api/tasks/useGetTasks.ts
  alta-front-end/src/api/topics/useGetTopics.ts
  alta-front-end/src/components/buttons/green-button.component.tsx
  alta-front-end/src/helpers/router/router.tsx
  alta-front-end/src/main.tsx
  alta-front-end/src/modules/students/content/table-columns.content.tsx
  alta-front-end/src/modules/students/students-table.component.tsx
  alta-front-end/src/modules/tasks/content/table-columns.content.tsx
  alta-front-end/src/modules/tasks/modal/modal-button.tsx
  alta-front-end/src/modules/tasks/tasks-table.component.tsx
  alta-front-end/src/modules/topics/topics-table.component.tsx
  alta-front-end/src/pages/tasks.tsx
  alta-front-end/src/pages/topics.tsx
Labels: frontend

#56 Get topic controller and topic service back
  alta-back-end/src/main/java/com/alta/entity/Zno.java
  alta-back-end/src/main/java/com/alta/facade/MainFacade.java
  alta-back-end/src/main/java/com/alta/facade/impl/DefaultMainFacade.java
  alta-back-end/src/main/java/com/alta/service/TopicService.java
  alta-back-end/src/main/java/com/alta/service/impl/DefaultTopicService.java
  alta-back-end/src/main/java/com/alta/web/controller/TopicController.java
Labels: backend

#61 added TasksRequest
  alta-front-end/src/api/topics/useGetTopics.ts
  alta-front-end/src/components/buttons/green-button.component.tsx
  alta-front-end/src/pages/topics/topics.tsx
Labels: backend, frontend

#63 added tasks table component
  alta-back-end/src/main/java/com/alta/repository/TopicRepository.java
  alta-front-end/src/pages/tasks/tasks-table.component.jsx.tsx
  alta-front-end/src/pages/tasks/tasks.tsx
  alta-front-end/src/pages/topics/topics.tsx
Labels: backend, frontend
